/**
 * Downloads the webfonts used by the site into public/fonts/ and writes the
 * matching @font-face rules to src/styles/fonts.css.
 *
 * Run with: node scripts/FetchFonts.mjs
 *
 * Self-hosting these removes a request to fonts.gstatic.com on every page view,
 * which would otherwise send each visitor's IP address to a third country
 * without a legal basis, and makes the site one round trip faster.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { basename } from "node:path";

const FAMILIES = "Jost:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500";
const CSS_URL = `https://fonts.googleapis.com/css2?family=${FAMILIES}&display=swap`;

// Google serves woff2 only to user agents it knows support it.
const MODERN_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) " +
  "Chrome/130.0.0.0 Safari/537.36";

const WANTED_SUBSETS = new Set(["latin", "latin-ext"]);

mkdirSync("public/fonts", { recursive: true });

const css = await (await fetch(CSS_URL, { headers: { "user-agent": MODERN_UA } })).text();

// Each @font-face block is preceded by a comment naming its subset.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];

const rules = [];

// Jost and IBM Plex Sans are variable fonts: every weight of a given subset
// resolves to the same file. Keying the cache on the remote URL stops the same
// bytes being written three times under three different names.
const fileNameByUrl = new Map();

for (const [, subset, block] of blocks) {
  if (!WANTED_SUBSETS.has(subset)) continue;

  const remoteUrl = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  if (remoteUrl === undefined) continue;

  let fileName = fileNameByUrl.get(remoteUrl);

  if (fileName === undefined) {
    const family = block.match(/font-family:\s*'([^']+)'/)?.[1] ?? "unknown";
    fileName = `${family.replace(/\s+/g, "")}-${subset}-${basename(remoteUrl)}`;

    const bytes = Buffer.from(await (await fetch(remoteUrl)).arrayBuffer());
    writeFileSync(`public/fonts/${fileName}`, bytes);
    fileNameByUrl.set(remoteUrl, fileName);
    console.log(`${fileName}  ${Math.round(bytes.length / 1024)} KB`);
  }

  rules.push(block.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url('/fonts/${fileName}')`).trim());
}

const downloaded = fileNameByUrl;

const header = [
  "/*",
  " * Generated by scripts/FetchFonts.mjs. Do not edit by hand.",
  " *",
  " * Fonts are served from this domain so that no visitor data reaches a third",
  " * party just to render text.",
  " */",
  "",
].join("\n");

writeFileSync("src/styles/fonts.css", `${header}${rules.join("\n\n")}\n`);
console.log(`\n${downloaded.size} ficheiros, ${rules.length} regras @font-face escritas em src/styles/fonts.css`);
